version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=${DB_SERVER};Database=PlanyDB;User=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=true
      - JWT__Key=${JWT_KEY}
      - JWT__Issuer=https://plany-api.japao.dev
      - JWT__Audience=https://plany-api.japao.dev
      - JWT__ExpiryInMinutes=60
      - EmailSettings__SmtpHost=${SMTP_HOST}
      - EmailSettings__SmtpPort=${SMTP_PORT}
      - EmailSettings__SmtpUser=${SMTP_USER}
      - EmailSettings__SmtpPass=${SMTP_PASS}
      - EmailSettings__EnableSsl=true
      - EmailSettings__FromAddress=${FROM_EMAIL}
      - EmailSettings__FromName=Plany
      - AppSettings__FrontendBaseUrl=${FRONTEND_URL}
      - AppSettings__PasswordResetTokenExpiryMinutes=60
      - InviteConfig__SecretKey=${INVITE_SECRET_KEY}
      - InviteConfig__AppDomain=${INVITE_APP_DOMAIN}
      - OpenAI__ApiKey=${OPENAI_API_KEY}
      - OpenAI__BaseUrl=${OPENAI_BASE_URL}
      - OpenAI__ModelName=${OPENAI_MODEL_NAME}
    networks:
      - plany-network
    restart: unless-stopped

networks:
  plany-network:
    driver: bridge
