// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PlanyApp.Repository.Models;

[Table("Categories")]
public partial class Category
{
    public Category()
    {
        Items = new HashSet<Item>();
    }

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int CategoryId { get; set; }

    [Required]
    [StringLength(255)]
    public string? Name { get; set; }

    public string? Description { get; set; }

    public virtual ICollection<Item> Items { get; set; }
}