// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanyApp.Repository.Models;

public partial class Category
{
    public string CategoryId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();
}