// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PlanyApp.Repository.Models;

[Table("Challenges")]
public partial class Challenge
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ChallengeId { get; set; }

    [Required]
    [StringLength(255)]
    public string? Name { get; set; }

    public string? Description { get; set; }

    public int? ItemId { get; set; }

    public int? PackageId { get; set; }

    public int? PointsAwarded { get; set; }

    [StringLength(50)]
    public string? DifficultyLevel { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public bool IsActive { get; set; }

    public int? CreatedByUserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    [ForeignKey("CreatedByUserId")]
    public virtual User? CreatedByUser { get; set; }

    [ForeignKey("ItemId")]
    public virtual Item? Item { get; set; }

    [ForeignKey("PackageId")]
    public virtual Package? Package { get; set; }

    public virtual ICollection<UserChallengeProgress> UserChallengeProgresses { get; set; } = new List<UserChallengeProgress>();
}