// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanyApp.Repository.Models;

public partial class Challenge
{
    public string ChallengeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string ItemId { get; set; }

    public string PackageId { get; set; }

    public int? PointsAwarded { get; set; }

    public string DifficultyLevel { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public bool IsActive { get; set; }

    public string CreatedByUserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual Item Item { get; set; }

    public virtual Package Package { get; set; }

    public virtual ICollection<UserChallengeProgress> UserChallengeProgresses { get; set; } = new List<UserChallengeProgress>();
}