// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanyApp.Repository.Models;

public partial class Group
{
    public string GroupId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string PlanId { get; set; }

    public DateTime GroupStart { get; set; }

    public DateTime GroupEnd { get; set; }

    public int TotalMember { get; set; }

    public string OwnerId { get; set; }

    public bool IsPrivate { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<GroupMember> GroupMembers { get; set; } = new List<GroupMember>();

    public virtual User Owner { get; set; }

    public virtual Plan Plan { get; set; }
}