// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PlanyApp.Repository.Models;

[Table("Groups")]
public partial class Group
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int GroupId { get; set; }

    [Required]
    [StringLength(255)]
    public string? Name { get; set; }

    public string? Description { get; set; }

    public int? PlanId { get; set; }

    public DateTime GroupStart { get; set; }

    public DateTime GroupEnd { get; set; }

    public int TotalMember { get; set; }

    public int OwnerId { get; set; }

    public bool IsPrivate { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<GroupMember> GroupMembers { get; set; } = new List<GroupMember>();

    [ForeignKey("OwnerId")]
    public virtual User? Owner { get; set; }

    [ForeignKey("PlanId")]
    public virtual Plan? Plan { get; set; }
}