// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanyApp.Repository.Models;

public partial class GroupMember
{
    public string GroupId { get; set; }

    public string UserId { get; set; }

    public decimal? CashContributed { get; set; }

    public DateTime JoinedAt { get; set; }

    public string RoleInGroup { get; set; }

    public virtual Group Group { get; set; }

    public virtual User User { get; set; }
}