// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanyApp.Repository.Models;

public partial class Image
{
    public string ImageId { get; set; }

    public string ReferenceType { get; set; }

    public string ReferenceId { get; set; }

    public byte[] ImageData { get; set; }

    public string ContentType { get; set; }

    public int? FileSizeKb { get; set; }

    public bool? IsPrimary { get; set; }

    public string Caption { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<UserChallengeProgress> UserChallengeProgresses { get; set; } = new List<UserChallengeProgress>();
}