// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PlanyApp.Repository.Models;

[Table("Images")]
public partial class Image
{
    public Image()
    {
        UserChallengeProgresses = new HashSet<UserChallengeProgress>();
    }

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ImageId { get; set; }

    [Required]
    [StringLength(50)]
    public string? ReferenceType { get; set; }

    public int ReferenceId { get; set; }

    [Required]
    public byte[]? ImageData { get; set; }

    [StringLength(100)]
    public string? ContentType { get; set; }

    public int? FileSizeKb { get; set; }

    public bool? IsPrimary { get; set; }

    public string? Caption { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<UserChallengeProgress> UserChallengeProgresses { get; set; }
}