// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PlanyApp.Repository.Models;

[Table("Invoices")]
public partial class Invoice
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int InvoiceId { get; set; }

    public int UserId { get; set; }

    public int? PackageId { get; set; }

    public DateTime InvoiceDate { get; set; }

    public DateTime? DueDate { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Discount { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    [Column(TypeName = "decimal(19, 2)")]
    public decimal? FinalAmount { get; set; }

    [Required]
    [StringLength(50)]
    public string? Status { get; set; }

    [StringLength(100)]
    public string? PaymentMethod { get; set; }

    [StringLength(255)]
    public string? TransactionId { get; set; }

    public string? Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    [ForeignKey("PackageId")]
    public virtual Package? Package { get; set; }

    [ForeignKey("UserId")]
    public virtual User? User { get; set; }
}