// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanyApp.Repository.Models;

public partial class Invoice
{
    public string InvoiceId { get; set; }

    public string UserId { get; set; }

    public string PackageId { get; set; }

    public DateTime InvoiceDate { get; set; }

    public DateTime? DueDate { get; set; }

    public decimal Amount { get; set; }

    public decimal Discount { get; set; }

    public decimal? FinalAmount { get; set; }

    public string Status { get; set; }

    public string PaymentMethod { get; set; }

    public string TransactionId { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Package Package { get; set; }

    public virtual User User { get; set; }
}