// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PlanyApp.Repository.Models;

[Table("Items")]
public partial class Item
{
    public Item()
    {
        Challenges = new HashSet<Challenge>();
        PlanLists = new HashSet<PlanList>();
        Ratings = new HashSet<Rating>();
    }

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ItemId { get; set; }

    [Required]
    [StringLength(50)]
    public string? ItemType { get; set; }

    public int? CategoryId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    [ForeignKey("CategoryId")]
    public virtual Category? Category { get; set; }

    public virtual ICollection<Challenge> Challenges { get; set; }

    public virtual Hotel? Hotel { get; set; }

    public virtual Place? Place { get; set; }

    public virtual ICollection<PlanList> PlanLists { get; set; }

    public virtual ICollection<Rating> Ratings { get; set; }

    public virtual Transportation? Transportation { get; set; }
}