// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PlanyApp.Repository.Models;

[Table("Packages")]
public partial class Package
{
    public Package()
    {
        Challenges = new HashSet<Challenge>();
        Invoices = new HashSet<Invoice>();
    }

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int PackageId { get; set; }

    [Required]
    [StringLength(255)]
    public string? Name { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }

    public string? Description { get; set; }

    public int? DurationDays { get; set; }

    [Required]
    [StringLength(50)]
    public string? Type { get; set; }

    [Required]
    [StringLength(50)]
    public string? Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Challenge> Challenges { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; }
}