// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanyApp.Repository.Models;

public partial class Place
{
    public string ItemId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public decimal? Price { get; set; }

    public string Description { get; set; }

    public TimeOnly? OpenTime { get; set; }

    public TimeOnly? CloseTime { get; set; }

    public virtual Item Item { get; set; }
}