// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PlanyApp.Repository.Models;

[Table("PlanList")]
public partial class PlanList
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int PlanListId { get; set; }

    public int PlanId { get; set; }

    public int ItemNo { get; set; }

    public int ItemId { get; set; }

    public int DayNumber { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public string? Notes { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Price { get; set; }

    [ForeignKey("ItemId")]
    public virtual Item? Item { get; set; }

    [ForeignKey("PlanId")]
    public virtual Plan? Plan { get; set; }
}
