// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PlanyApp.Repository.Models;

[Table("Plans")]
public partial class Plan
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int PlanId { get; set; }

    [Required]
    [StringLength(255)]
    public string? Name { get; set; }

    public int DayCount { get; set; }

    public int NightCount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal TotalCost { get; set; }

    public int OwnerId { get; set; }

    public bool IsPublic { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string? Description { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();

    [ForeignKey("OwnerId")]
    public virtual User? Owner { get; set; }

    public virtual ICollection<PlanList> PlanLists { get; set; } = new List<PlanList>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();
}
