// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanyApp.Repository.Models;

public partial class Plan
{
    public string PlanId { get; set; }

    public string Name { get; set; }

    public DateTime DateCreated { get; set; }

    public int DayCount { get; set; }

    public int NightCount { get; set; }

    public decimal TotalCost { get; set; }

    public string OwnerId { get; set; }

    public string Status { get; set; }

    public bool IsPublic { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();

    public virtual User Owner { get; set; }

    public virtual ICollection<PlanList> PlanLists { get; set; } = new List<PlanList>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();
}