// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PlanyApp.Repository.Models;

[Table("Ratings")]
public partial class Rating
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int RatingId { get; set; }

    public int? PlanId { get; set; }

    public int? ItemId { get; set; }

    public int UserId { get; set; }

    public int Rate { get; set; }

    public string? Comment { get; set; }

    public DateTime DatePosted { get; set; }

    public DateTime CreatedAt { get; set; }

    [ForeignKey("ItemId")]
    public virtual Item? Item { get; set; }

    [ForeignKey("PlanId")]
    public virtual Plan? Plan { get; set; }

    [ForeignKey("UserId")]
    public virtual User? User { get; set; }
}