// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanyApp.Repository.Models;

public partial class Rating
{
    public string RatingId { get; set; }

    public string PlanId { get; set; }

    public string ItemId { get; set; }

    public string UserId { get; set; }

    public int Rate { get; set; }

    public string Comment { get; set; }

    public DateTime DatePosted { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Item Item { get; set; }

    public virtual Plan Plan { get; set; }

    public virtual User User { get; set; }
}