// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlanyApp.Repository.Models;

public partial class UserChallengeProgress
{
    public string UserChallengeProgressId { get; set; }

    public string UserId { get; set; }

    public string ChallengeId { get; set; }

    public string Status { get; set; }

    public DateTime? StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public string ProofImageId { get; set; }

    public string VerificationNotes { get; set; }

    public int? PointsEarned { get; set; }

    public virtual Challenge Challenge { get; set; }

    public virtual Image ProofImage { get; set; }

    public virtual User User { get; set; }
}