// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PlanyApp.Repository.Models;

[Table("Users")]
public class User
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    public string FullName { get; set; }

    [Required]
    [StringLength(255)]
    [EmailAddress]
    public string Email { get; set; }

    [Required]
    [StringLength(255)]
    public string PasswordHash { get; set; }

    [StringLength(15)]
    public string? Phone { get; set; }

    [StringLength(255)]
    public string? Address { get; set; }

    [StringLength(255)]
    public string? Avatar { get; set; }

    public int? RoleId { get; set; }

    [StringLength(255)]
    public string? GoogleId { get; set; } // For Google OAuth

    public bool EmailVerified { get; set; } // For email verification

    [StringLength(255)]
    public string? PasswordResetToken { get; set; } // For password reset

    public DateTime? PasswordResetTokenExpiresAt { get; set; } // Expiry for password reset token

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime CreatedDate { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime UpdatedDate { get; set; }

    // Navigation properties
    [ForeignKey("RoleId")]
    public virtual Role? Role { get; set; }
    public virtual ICollection<Booking> BookingsNavigation { get; set; } = new List<Booking>();
    public virtual ICollection<UserPlan> UserPlansNavigation { get; set; } = new List<UserPlan>();
    public virtual ICollection<GroupUser> GroupUsersNavigation { get; set; } = new List<GroupUser>();
    public virtual ICollection<Rating> RatingsNavigation { get; set; } = new List<Rating>();
}