name: build n deploy plany

on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy with Docker Compose
      run: |
        docker compose down
        docker compose up --build -d 