name: build n deploy plany

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  IMAGE_NAME: plany_be

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest

    - name: Deploy application
      run: |
        if [ $(docker ps -q -f name=plany_be) ]; then
          docker stop plany_be
          docker rm plany_be
        fi
        docker run -d -p 8080:8080 -p 8443:443 --env-file /root/lol/.env --name plany_be $IMAGE_NAME:latest 